export const RESTRICTIONS = [
  { id: 'sin-tacc', label: 'Sin TACC / Celíaco', color: '#e63946' },
  { id: 'apto-diabeticos', label: 'Apto Diabéticos', color: '#2a9d8f' },
  { id: 'sin-lactosa', label: 'Sin Lactosa', color: '#e9a824' },
  { id: 'apto-sibo', label: 'Apto SIBO', color: '#457b9d' },
]

export const BUSINESS_TYPES = [
  { id: 'restaurante', label: 'Restaurante', color: '#e63946' },
  { id: 'dietetica', label: 'Dietética', color: '#2a9d8f' },
  { id: 'supermercado', label: 'Supermercado', color: '#264653' },
  { id: 'cafe', label: 'Café', color: '#b5838d' },
]

export const CERTIFICATIONS = {
  RNE: 'Registro Nacional de Establecimientos',
  CMA: 'Carnet de Manipulador de Alimentos',
  DJPS: 'Declaración Jurada de Proveedores Seguros',
  RNPA: 'Registro Nacional de Producto Alimenticio',
  ELISA: 'Enzyme-Linked Immunosorbent Assay (Ensayo por Inmunoabsorción Ligado a Enzimas)',
}

export const mockBusinesses = [
  {
    id: 1,
    name: 'La Mesa Sin TACC',
    type: 'restaurante',
    address: 'Av. Hipólito Yrigoyen 1200, Nueva Córdoba',
    lat: -31.419,
    lng: -64.1875,
    phone: '0351-423-1234',
    whatsapp: '5493514231234',
    openingHours: [
      { day: 'lunes',     open: '12:00', close: '23:30', closed: false },
      { day: 'martes',    open: '12:00', close: '23:30', closed: false },
      { day: 'miércoles', open: '12:00', close: '23:30', closed: false },
      { day: 'jueves',    open: '12:00', close: '23:30', closed: false },
      { day: 'viernes',   open: '12:00', close: '23:30', closed: false },
      { day: 'sábado',    open: '12:00', close: '23:30', closed: false },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: 'https://instagram.com/lamesasintacc',
    websiteUrl: 'https://lamesasintacc.com.ar',
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Restaurante especializado 100% libre de gluten. Todos nuestros platos son preparados en ambientes separados con certificación RNPA y RNE.',
    tags: ['sin-tacc'],
    certifications: ['RNPA', 'RNE', 'CMA'],
    verified: true,
    rating: 4.8,
    menu: [
      { name: 'Milanesa de soja sin TACC', price: 3200 },
      { name: 'Pizza base de maíz y arroz', price: 3800 },
      { name: 'Empanadas sin gluten (x6)', price: 2600 },
      { name: 'Pasta fresca sin gluten', price: 3400 },
    ],
    pending: false,
  },
  {
    id: 2,
    name: 'Dietética NaturAlma',
    type: 'dietetica',
    address: 'Bv. San Juan 845, General Paz',
    lat: -31.405,
    lng: -64.187,
    phone: '0351-462-5678',
    whatsapp: '5493514625678',
    openingHours: [
      { day: 'lunes',     open: '09:00', close: '20:30', closed: false },
      { day: 'martes',    open: '09:00', close: '20:30', closed: false },
      { day: 'miércoles', open: '09:00', close: '20:30', closed: false },
      { day: 'jueves',    open: '09:00', close: '20:30', closed: false },
      { day: 'viernes',   open: '09:00', close: '20:30', closed: false },
      { day: 'sábado',    open: '09:00', close: '13:00', closed: false },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: 'https://instagram.com/dieteticanaturalma',
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Dietética con amplia variedad de productos para celiaquía, diabetes e intolerancia a la lactosa. Asesoramiento nutricional.',
    tags: ['sin-tacc', 'apto-diabeticos', 'sin-lactosa'],
    certifications: ['RNPA', 'CMA'],
    verified: true,
    rating: 4.6,
    menu: [
      { name: 'Harinas sin TACC (variedad)', price: 1200 },
      { name: 'Edulcorantes naturales', price: 890 },
      { name: 'Leches vegetales', price: 1450 },
      { name: 'Snacks sin gluten', price: 780 },
      { name: 'Pastas secas aptas', price: 980 },
    ],
    pending: false,
  },
  {
    id: 3,
    name: 'Café Consciente',
    type: 'cafe',
    address: 'Calle Obispo Trejo 234, Centro',
    lat: -31.4135,
    lng: -64.1815,
    phone: '0351-471-9012',
    whatsapp: '5493514719012',
    openingHours: [
      { day: 'lunes',     open: '08:00', close: '22:00', closed: false },
      { day: 'martes',    open: '08:00', close: '22:00', closed: false },
      { day: 'miércoles', open: '08:00', close: '22:00', closed: false },
      { day: 'jueves',    open: '08:00', close: '22:00', closed: false },
      { day: 'viernes',   open: '08:00', close: '22:00', closed: false },
      { day: 'sábado',    open: '08:00', close: '22:00', closed: false },
      { day: 'domingo',   open: '08:00', close: '22:00', closed: false },
    ],
    instagramUrl: 'https://instagram.com/cafeconscienteresto',
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Café con opciones para todos los perfiles dietéticos. Bebidas vegetales, repostería sin gluten y opciones bajas en azúcar.',
    tags: ['sin-tacc', 'sin-lactosa', 'apto-sibo'],
    certifications: ['CMA', 'RNE'],
    verified: true,
    rating: 4.5,
    menu: [
      { name: 'Café con leche de avena', price: 1200 },
      { name: 'Muffin sin gluten y sin lactosa', price: 980 },
      { name: 'Tostado de pan sin TACC', price: 1450 },
      { name: 'Smoothie sin azúcar', price: 1650 },
    ],
    pending: false,
  },
  {
    id: 4,
    name: 'Supermercado El Verde',
    type: 'supermercado',
    address: 'Av. Rafael Núñez 3456, Cerro de las Rosas',
    lat: -31.38,
    lng: -64.208,
    phone: '0351-489-3456',
    whatsapp: '5493514893456',
    openingHours: [
      { day: 'lunes',     open: '08:00', close: '21:00', closed: false },
      { day: 'martes',    open: '08:00', close: '21:00', closed: false },
      { day: 'miércoles', open: '08:00', close: '21:00', closed: false },
      { day: 'jueves',    open: '08:00', close: '21:00', closed: false },
      { day: 'viernes',   open: '08:00', close: '21:00', closed: false },
      { day: 'sábado',    open: '08:00', close: '21:00', closed: false },
      { day: 'domingo',   open: '09:00', close: '13:00', closed: false },
    ],
    instagramUrl: null,
    websiteUrl: 'https://elverde.com.ar',
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Supermercado especializado en productos saludables. Amplia sección sin TACC, sección diabéticos y productos sin lactosa.',
    tags: ['sin-tacc', 'apto-diabeticos', 'sin-lactosa', 'apto-sibo'],
    certifications: ['RNPA', 'CMA'],
    verified: true,
    rating: 4.3,
    menu: [
      { name: 'Sección Sin TACC', price: null },
      { name: 'Sección Diabéticos', price: null },
      { name: 'Sección Sin Lactosa', price: null },
      { name: 'Productos orgánicos', price: null },
    ],
    pending: false,
  },
  {
    id: 5,
    name: 'Rincón Vegano & Sin Gluten',
    type: 'restaurante',
    address: 'Av. Figueroa Alcorta 678, Güemes',
    lat: -31.428,
    lng: -64.194,
    phone: '0351-455-7890',
    whatsapp: '5493514557890',
    openingHours: [
      { day: 'lunes',     open: '00:00', close: '00:00', closed: true  },
      { day: 'martes',    open: '12:00', close: '23:00', closed: false },
      { day: 'miércoles', open: '12:00', close: '23:00', closed: false },
      { day: 'jueves',    open: '12:00', close: '23:00', closed: false },
      { day: 'viernes',   open: '12:00', close: '23:00', closed: false },
      { day: 'sábado',    open: '12:00', close: '23:00', closed: false },
      { day: 'domingo',   open: '12:00', close: '23:00', closed: false },
    ],
    instagramUrl: 'https://instagram.com/rinconvegano',
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Propuesta gastronómica 100% vegana y libre de gluten. Especialistas en cocina para personas con restricciones múltiples.',
    tags: ['sin-tacc', 'sin-lactosa', 'apto-sibo'],
    certifications: ['RNPA', 'RNE', 'CMA'],
    verified: true,
    rating: 4.7,
    menu: [
      { name: 'Bowl de quinoa con verduras', price: 3400 },
      { name: 'Hamburguesa vegana sin gluten', price: 3800 },
      { name: 'Tiramisú de coco sin gluten', price: 1800 },
      { name: 'Sopa de zapallo y jengibre', price: 2400 },
    ],
    pending: false,
  },
  {
    id: 6,
    name: 'Panadería Sin Límites',
    type: 'dietetica',
    address: 'Calle Lima 567, Alberdi',
    lat: -31.4125,
    lng: -64.2025,
    phone: '0351-433-2345',
    whatsapp: '5493514332345',
    openingHours: [
      { day: 'lunes',     open: '07:00', close: '20:00', closed: false },
      { day: 'martes',    open: '07:00', close: '20:00', closed: false },
      { day: 'miércoles', open: '07:00', close: '20:00', closed: false },
      { day: 'jueves',    open: '07:00', close: '20:00', closed: false },
      { day: 'viernes',   open: '07:00', close: '20:00', closed: false },
      { day: 'sábado',    open: '07:00', close: '20:00', closed: false },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: 'https://instagram.com/panaderiasinlimites',
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Panadería artesanal especializada en productos sin gluten. Pan fresco diario, facturas y repostería sin TACC.',
    tags: ['sin-tacc'],
    certifications: ['RNE', 'CMA', 'RNPA'],
    verified: true,
    rating: 4.9,
    menu: [
      { name: 'Pan de molde sin TACC (500g)', price: 1800 },
      { name: 'Facturas sin gluten (x6)', price: 2200 },
      { name: 'Galletas de arroz', price: 950 },
      { name: 'Torta sin gluten', price: 4500 },
    ],
    pending: false,
  },
  {
    id: 7,
    name: 'El Ranchito Saludable',
    type: 'restaurante',
    address: 'Av. Colón 2890, Centro',
    lat: -31.416,
    lng: -64.182,
    phone: '0351-477-6789',
    whatsapp: '5493514776789',
    openingHours: [
      { day: 'lunes',     open: '12:00', close: '22:30', closed: false },
      { day: 'martes',    open: '12:00', close: '22:30', closed: false },
      { day: 'miércoles', open: '12:00', close: '22:30', closed: false },
      { day: 'jueves',    open: '12:00', close: '22:30', closed: false },
      { day: 'viernes',   open: '12:00', close: '22:30', closed: false },
      { day: 'sábado',    open: '00:00', close: '00:00', closed: true  },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: null,
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Restaurante con menú diseñado para diabéticos. Todos los platos con índice glucémico controlado y sin azúcares añadidos.',
    tags: ['apto-diabeticos', 'sin-lactosa'],
    certifications: ['RNPA', 'CMA'],
    verified: true,
    rating: 4.4,
    menu: [
      { name: 'Pollo grillado con ensalada', price: 3600 },
      { name: 'Pasta integral con salsa de tomate', price: 3200 },
      { name: 'Sopa de legumbres', price: 2400 },
      { name: 'Postre sin azúcar', price: 1600 },
    ],
    pending: false,
  },
  {
    id: 8,
    name: 'BienestarMar - Nutrición',
    type: 'dietetica',
    address: 'Bv. Chacabuco 1200, Nueva Córdoba',
    lat: -31.422,
    lng: -64.185,
    phone: '0351-488-1234',
    whatsapp: '5493514881234',
    openingHours: [
      { day: 'lunes',     open: '09:00', close: '21:00', closed: false },
      { day: 'martes',    open: '09:00', close: '21:00', closed: false },
      { day: 'miércoles', open: '09:00', close: '21:00', closed: false },
      { day: 'jueves',    open: '09:00', close: '21:00', closed: false },
      { day: 'viernes',   open: '09:00', close: '21:00', closed: false },
      { day: 'sábado',    open: '00:00', close: '00:00', closed: true  },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: 'https://instagram.com/bienestarmar',
    websiteUrl: null,
    status: 'aprobado',
    ownerEmail: null,
    description:
      'Centro de nutrición especializado en SIBO y patologías digestivas. Suplementos, probióticos y asesoramiento personalizado.',
    tags: ['apto-sibo', 'sin-tacc', 'sin-lactosa'],
    certifications: ['RNPA', 'CMA'],
    verified: true,
    rating: 4.6,
    menu: [
      { name: 'Suplementos para SIBO', price: 3200 },
      { name: 'Probióticos especializados', price: 4500 },
      { name: 'Alimentos fermentados', price: 1800 },
      { name: 'Consulta nutricional', price: 6000 },
    ],
    pending: false,
  },
  {
    id: 9,
    name: 'Sano y Rico',
    type: 'restaurante',
    address: 'Calle Mendoza 890, Nueva Córdoba',
    lat: -31.4195,
    lng: -64.19,
    phone: '0351-499-5678',
    whatsapp: '5493514995678',
    openingHours: [
      { day: 'lunes',     open: '11:00', close: '23:00', closed: false },
      { day: 'martes',    open: '11:00', close: '23:00', closed: false },
      { day: 'miércoles', open: '11:00', close: '23:00', closed: false },
      { day: 'jueves',    open: '11:00', close: '23:00', closed: false },
      { day: 'viernes',   open: '11:00', close: '23:00', closed: false },
      { day: 'sábado',    open: '11:00', close: '23:00', closed: false },
      { day: 'domingo',   open: '11:00', close: '23:00', closed: false },
    ],
    instagramUrl: null,
    websiteUrl: null,
    status: 'pendiente',
    ownerEmail: null,
    description:
      'Nuevo restaurante con opciones saludables para diversas restricciones alimentarias.',
    tags: ['sin-tacc', 'apto-diabeticos'],
    certifications: ['RNPA'],
    verified: false,
    rating: null,
    menu: [
      { name: 'Ensalada proteica', price: 2800 },
      { name: 'Bowl sin gluten', price: 3200 },
    ],
    pending: true,
  },
  {
    id: 10,
    name: 'La Despensa Natural',
    type: 'supermercado',
    address: 'Av. Ambrosio Olmos 456, Alta Córdoba',
    lat: -31.4,
    lng: -64.179,
    phone: '0351-411-2345',
    whatsapp: '5493514112345',
    openingHours: [
      { day: 'lunes',     open: '08:00', close: '21:00', closed: false },
      { day: 'martes',    open: '08:00', close: '21:00', closed: false },
      { day: 'miércoles', open: '08:00', close: '21:00', closed: false },
      { day: 'jueves',    open: '08:00', close: '21:00', closed: false },
      { day: 'viernes',   open: '08:00', close: '21:00', closed: false },
      { day: 'sábado',    open: '08:00', close: '21:00', closed: false },
      { day: 'domingo',   open: '00:00', close: '00:00', closed: true  },
    ],
    instagramUrl: null,
    websiteUrl: null,
    status: 'pendiente',
    ownerEmail: null,
    description:
      'Despensa de productos naturales y orgánicos con amplia sección para alergias e intolerancias.',
    tags: ['sin-tacc', 'sin-lactosa', 'apto-diabeticos'],
    certifications: ['RNPA', 'CMA'],
    verified: false,
    rating: null,
    menu: [],
    pending: true,
  },
]

export const BUSINESS_TYPE_MAP = Object.fromEntries(BUSINESS_TYPES.map((t) => [t.id, t]))
export const RESTRICTION_MAP = Object.fromEntries(RESTRICTIONS.map((r) => [r.id, r]))
